config/routes.rb
Games::Application.routes.draw do
  
  root :to => "games#index"
  
  resources :games do
    resources :hands
    member do
      put 'recalc'
    end    
  end
    
  
  resources :players
  
  resources :dashboards do 
    collection do
      get 'game_time_line'
    end
  end
  
end

app/models/game.rb
class Game
  
  @@game_types = {
    phase_10: {name: "Phase Ten", rules_class: :phase_ten},
    five_crowns: {name: "5 Crowns", rules_class: :five_crowns}
  }
  
  include Mongoid::Document
  include Mongoid::Timestamps  

  validates_presence_of :game_type, :message => "You need to include a game type"
  validates_presence_of :play_date, :message => "You need to include a play date"  

  field :play_date, type: Time, default: Time.now
  field :game_type, type: Symbol  
  field :winner_id, type: BSON::ObjectId

  has_and_belongs_to_many :players
  embeds_many :hands
  
  def self.game_types
    @@game_types
  end
  
  
  def self.create_it(game: nil)
    g = Game.new(game)
    g.save
    g
  end
  
  def delete_it
    self.destroy
    self
  end

  def game_name
    @@game_types[self.game_type][:name]
  end
  
  def rules
    GameRules.rules_factory(game: @@game_types[self.game_type][:rules_class])
  end
  
  def has_a_winner
    self.winner_id ? true : false
  end
  
  def winner
    Player.find(winner_id)
  end
  
  def duration
    if self.hands.present?
      Time.at(self.hands.last.updated_at - self.play_date).utc.strftime("%H:%M:%S")
    else
      Time.at(Time.now - self.play_date).utc.strftime("%H:%M:%S")
    end
  end
  

end

app/models/hand.rb
class Hand
  
  
  include Mongoid::Document
  include Mongoid::Timestamps  

  field :seq, type: Integer
  field :duration, type: Date

  embedded_in :game
  
  embeds_many :scores
  
  def self.game_types
    @@game_types
  end
  
  
  def self.create_it(hand: nil, seq: 1)
    h = Hand.new.add_scores(hand_scores: hand, seq: seq)
    h
  end

  def add_scores(hand_scores: nil, seq: 1)
    hand_scores.each {|player, score| 
      s = Score.new.add_score(score: score)
      scores << s
    }
    self.seq = seq
    self
  end
  
  def score(player: nil)
    self.scores.where(player_id: player.id).first
  end

end

app/models/player.rb
class Player
  
  include Mongoid::Document
  include Mongoid::Timestamps  
  
  
  field :name, :type => String
  
  validates_uniqueness_of :name
  
  has_and_belongs_to_many :games
  

  def self.create_it(params)
    player = self.new(params)
    player.save
    player
  end
  
  def update_it(params)
    self.attributes = (params[:player])
    save
  end
  
  def number_of_wins
    Game.where(winner_id: self.id).count
  end
  
  def played
    self.games.count
  end

end

app/models/score.rb
class Score
  
  
  include Mongoid::Document
  include Mongoid::Timestamps  

  field :score, type: Integer
  field :player_id, type: BSON::ObjectId
  field :accumulate, type: Integer
  field :hand_winner, type: Boolean
  field :achieved, type: Boolean
  field :obtained, type: Symbol

  validates_presence_of :score, :message => "Player must have a score"

  embedded_in :hand

  def add_score(score: nil)
    self.score = score[:score]
    self.player_id = Player.find(score[:player_id]).id
    self
  end
  
  def player
    Player.find(self.player_id)
  end
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def build_flash_errors(model)
    if model.errors.any?
      flash[:errors] = model.errors.messages
    end
  end

  def build_multiple_flash_errors(*models)
    flash[:errors] = {}
    models.flatten.each do |model|
      if model.errors.any?
        flash[:errors][model.class.to_s.downcase.to_sym] = model.errors.messages
      end
    end
  end
  
  
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  
  def game_time_line
    @game = Game.find(params[:game])
    @play = PlayGame.new
    @play.create_time_line(game: @game)
    respond_to do |format|
      format.js {render 'time_line'}
    end
  end
  
  def time_line_event
  end
  
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  
  def index
    @games = Game.all
    respond_to do |format|
      format.html
    end
  end
  
  def new
    @game = Game.new
    @players = Player.all
  end
  
  def create
    @game = Game.create_it(game: params[:game])
    respond_to do |format|
      if @game.valid?
        format.html { redirect_to games_path }
      else
        build_flash_errors(@game)
        format.html { render action: "new" }
      end
    end      
  end
  
  def show
    @game = Game.find(params[:id])
    @rules = @game.rules
    respond_to do |format|
      format.html
    end
    
  end
  
  def edit
    @game = Game.find(params[:id]) if !@game    
  end
  
  def update
    @game = Game.find(params[:id])    
    @game.update_it(params)
    respond_to do |format|
      if @game.valid?
        format.html { redirect_to games_path }
      else
        format.html { render action: "edit" }
      end
    end      
    
  end
  
  def destroy
    @game = Game.find(params[:id])    
    @game.delete_it
    respond_to do |format|
      if @game.valid?
        format.html { redirect_to games_path }
      else
        format.html { render action: "edit" }
      end
    end      
  end
    
  def recalc
    game = Game.find(params[:id])
    pg = PlayGame.new
    pg.add_subscriber(self)        
    pg.re_calc_game(game: game)
  end
  
  def game_recaled(game)
    respond_to do |f|
      f.html {redirect_to game_path game }
    end
  end
  
  
end

app/controllers/hands_controller.rb
class HandsController < ApplicationController
  
  def index
  end
  
  def new
    @game = Game.find(params[:game_id])
    @rules = @game.rules
    @hand = Hand.new
    respond_to do |format|
      format.js {render 'hand_form', :layout => false }
    end
  end
  
  
  # "hand"=>{"Juki"=>{"score"=>"10", "player_id"=>"537a68b74d617403c3000000"}, "Col"=>{"score"=>"20", "player_id"=>"537be4e04d6174105e000000"}}
  
  def create
    game = Game.find(params[:game_id])
    hand = PlayGame.new
    hand.add_subscriber(self)        
    hand.play_hand(game: game, hand: params[:hand])
  end
        
  
  def game_hand_played(game)
    respond_to do |f|
      f.html {redirect_to game_path game }
    end
  end

  def game_hand_errors(game, hand)
    respond_to do |f|
      build_multiple_flash_errors(game, hand, hand.scores)
      f.html {redirect_to game_path game }
    end
  end

  
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  
  def index
    @players = Player.all
    respond_to do |format|
      format.html
      format.json
    end
  end
  
  def new
    @player = Player.new
  end
  
  def create
    @player = Player.create_it(params[:player])
    respond_to do |format|
      if @player.valid?
        format.html { redirect_to players_path }
        format.json
      else
        format.html { render action: "new" }
        format.json
      end
    end      
  end
  
  def show
    @player = Player.find(params[:id]) if !@player
  end
  
  def edit
    @player = Player.find(params[:id]) if !@player    
  end
  
  def update
    @player = Player.find(params[:id])    
    @player.update_it(params)
    respond_to do |format|
      if @player.valid?
        format.html { redirect_to players_path }
        format.json
      else
        format.html { render action: "edit" }
        format.json
      end
    end      
    
  end
    
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def game_types_select
    Game.game_types.map {|type, conf| [conf[:name], type]}
  end
  
  def player_list_select_old
    Player.all.map {|p| [p.name, p.id]}
  end
  
  def player_list_select
    Player.all.map {|p| [p.name]}
  end
  
end

app/views/games/_form.html.erb
<div class='alert alert-info fade in' data-alert='alert'>
   <h3>Games</h3>
</div>

<%= simple_form_for @game,  as: 'game', html: { class: 'form-horizontal' },
  wrapper: :horizontal_form,
  wrapper_mappings: {
    check_boxes: :horizontal_radio_and_checkboxes,
    radio_buttons: :horizontal_radio_and_checkboxes,
    file: :horizontal_file_input,
    boolean: :horizontal_boolean
  } do |f| %>
   <%= render partial: 'shared/flash_errors'%>
   <%= f.input :play_date, placeholder: "Enter Play Date"%>
   <%= f.input :game_type, collection: Game.game_types %>
   <%= f.association :players, label_method: :name, value_method: :id %>   
   <%= f.button :submit %>
<% end %>

app/views/games/_hand.html.erb
<tr>
   <td><%= @rules.hand_name(hand: hand)%></td>
   <% for player in @game.players %>
      <% player_score = hand.score(player: player)%>
      <td>
         <% if player_score.hand_winner%>
            <div class="alert alert-warning">
         <% end %>
            <p>
               <span class="label label-info"><%= player_score.score %></span>
               <span class="label label-success"><%= player_score.accumulate %></span>
               <% if player_score.achieved %>
                  <span class="label label-primary">
                     <span class="glyphicon glyphicon-ok"><%= @rules.obtained(sym: player_score.obtained)%></span>
                  </span>             
               <% end %>
               <span class="label label-warning">
                  <span >
                    <% if @rules.has_obtains%>
                      <%= @rules.next_to_obtain(hand: hand, hands: @game.hands, player: player)%>
                    <% end %>
                  </span>
               </span>                         
            </p>
         <% if player_score.hand_winner%>
            </div>
         <% end %>
      </td>
   <% end %>
</tr>

app/views/games/_winner_line.html.erb
<tr>
   <td>Final</td>
   <% for player in game.players %>
      <% player_score = hand.score(player: player)%>
      <td>
         <% if player_score.player_id == game.winner_id%>
            <span class="label label-danger">
               <span class="glyphicon glyphicon-ok">Winner</span>           
            </span>
         <% end %>
      </td>
   <% end %>
</tr>

app/views/games/index.html.erb
<div class='alert alert-info fade in' data-alert='alert'>
   <h3>Games</h3>
</div>

<table class="table">
   <thead>
     <tr>
       <th>Date</th>
       <th>Game</th>
       <th>Duration</th>
       <th>Winner</th>      
       <th>Players</th>             
       <th>Actions</th>      
     </tr>
   </thead>
   <tbody>
      <% for game in @games %>         
         <tr>
            <td>
               <%= game.play_date %>
            </td>
            <td>
               <%= game.game_name %>
            </td>
            <td>
               <%= game.duration %>
            </td>
            <td>
               <span class="label label-danger"><%= game.winner.name if game.has_a_winner%></span>
            </td>
            <td>
               <% game.players.each do |p| %>
                  <span class="label label-success"><%= p.name %></span>
               <% end %>
            </td>

            <td>
               <%= link_to("Play",  game_path(game), class: 'btn btn-default') if !game.has_a_winner%>
               <%= link_to("View",  game_path(game), class: 'btn btn-default') if game.has_a_winner%>               
               <%= link_to "Delete",  game_path(game), method: :delete, class: 'btn btn-danger'%>                  
            </td>
         </tr>
      <% end %>
   </tbody>
</table>

app/views/games/new.html.erb
<%= render partial: "form" %>

app/views/games/show.html.erb
<div class="jumbotron">
   <div class="row">
      <div class="col-md-4">
         <h1><%= @rules.name%></h1>
         <% if !@game.has_a_winner %>
            <p><%= link_to "New Hand", new_game_hand_path(@game), class: "btn btn-primary", role: "button", remote: true %></p>
         <% end %>
         <p><%= link_to 'Re_Calc', recalc_game_path(@game), class: "btn btn-primary", method: :put%>
         <p><%= link_to 'TIme Line', game_time_line_dashboards_path(game: @game), class: "btn btn-primary", remote: true %>
            
      </div>
      <div class="col-md-4">
         <p><%= @game.winner.name if @game.has_a_winner%></p>
         <p>Hands: <%= @game.hands.count%></p>
      </div>
      <div class="col-md-4">
         <% if @rules.has_obtains%>
            <% @rules.obtains.each do |key, names| %>
               <% @rules.highest_obtains(hands: @game.hands) == key ? highlight = "warning" : highlight = "primary"  %>
               <h4><span class="label label-<%=highlight%>"><%= names[:name]%></scan></h4>
            <% end %>
         <% end %>
      </div>      
   </div>
   
   <div class="row">
      <table class="table">
         <thead>
           <tr>
              <th>Hand</th>
               <% for player in @game.players %>
                  <th><%= player.name %></th>
               <% end %>
           </tr>
         </thead>
         <tbody>
            <%= render partial: 'hand', locals: {hand: @game.hands.last} if @game.hands.count > 0 %>
         </tbody>
      </table>  
   </div>
   
</div>

<%= render partial: 'shared/flash_errors'%>

<div id="new_hand"></div>

<div id="timeline_chart"></div>

<div class="jumbotron">

   <table class="table">
      <thead>
        <tr>
           <th>Hand</th>
            <% for player in @game.players %>
               <th><%= player.name %></th>
            <% end %>
        </tr>
      </thead>
      <tbody>
         <% for hand in @game.hands %> 
            <%= render partial: 'hand', locals: {hand: hand}%>
         <% end %>
         <%= render(partial: 'winner_line', locals: {game: @game, hand: hand}) if @game.has_a_winner %>
      </tbody>
   </table>

</div>

app/views/hands/_form.html.erb
<%= simple_form_for [@game, @hand], as: 'hand',
  defaults: { label: false },
  html: { class: 'form-inline' },
  wrapper_mappings: {
    boolean: :vertical_boolean
  } do |f| %>
   <% for player in @game.players %>
        <%= f.simple_fields_for player.name.to_sym do |sf| %>
           <%= sf.input :score, placeholder: "Score", label: player.name %>
           <%= sf.hidden_field :player_id, value: player.id %>        
      <% end %>
   <% end %>

  <%= f.button :submit%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Games" %></title>
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
<header class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Game It</a>
        </div>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Games <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "List", games_path %></li>
                <li><%= link_to "New", new_game_path %></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Players <b class="caret"></b></a>
              <ul class="dropdown-menu">
                 <li><%= link_to "List", players_path %></li>
                 <li><%= link_to "New", new_player_path %></li>
              </ul>
            </li>
          </ul>          
      </div>
    </div>
  </header>

<div class="container master-container">
    <ul class="breadcrumb">
      <%= yield :breadcrumb %>
    </ul>

    <% if notice %>
      <div class="alert alert-success fade in" data-alert="alert">
        <a class="close" data-dismiss='alert' href="#">×</a>
        <p><%= notice %></p>
      </div>
    <% end %>

    <%= yield %>
    
  </div>

    
  </body>
</html>

app/views/players/_form.html.erb
<div class='alert alert-info fade in' data-alert='alert'>
   <h3>Players</h3>
</div>

<%= simple_form_for @player,  as: 'player', html: { class: 'form-horizontal' },
  wrapper: :horizontal_form,
  wrapper_mappings: {
    check_boxes: :horizontal_radio_and_checkboxes,
    radio_buttons: :horizontal_radio_and_checkboxes,
    file: :horizontal_file_input,
    boolean: :horizontal_boolean
  } do |f| %>
   <%= f.input :name, label: "Name" %>
   <%= f.button :submit %>
<% end %>

app/views/players/index.html.erb
<div class='alert alert-info fade in' data-alert='alert'>
   <h3>Players</h3>
</div>

<table class="table">
   <thead>
     <tr>
       <th>Name</th>
       <th>Wins</th>
       <th>Played</th>
       <th>Actions</th>      
     </tr>
   </thead>
   <tbody>
      <% for player in @players %>         
         <tr>
            <td>
               <%= link_to player.name, player_path(player)%>
            </td>
            <td><%= player.number_of_wins %></td>
            <td><%= player.played %></td>
            <td>
               <%= link_to "Show",  player_path(player), class: "btn btn-default"%>
            </td>
         </tr>
      <% end %>
   </tbody>
</table>

app/views/players/new.html.erb
<%= render partial: "form" %>

app/views/shared/_flash_errors.html.erb
<% if flash[:errors]%>
	<div class="alert alert-error">
		<p class="lead"><%= pluralize(flash[:errors].count, "error") %> found:</p>
		<ul>
			<% flash[:errors].each do |model, messages| %>
            <% messages.each do |attribute, msg| %>
               <li><%= "#{model}: #{attribute}: #{msg}" %></li>
            <% end %>
			<% end %>
		</ul>
	</div>
<% end %>